### Word Embedding Techniques using Embedding Layer in Keras

In [1]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your pics are good',]

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your pics are good']

In [6]:
### Vocabulary size
voc_size=10000

#### One Hot Representation

In [7]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[807, 7871, 1888, 5861], [807, 7871, 1888, 9764], [807, 9155, 1888, 3730], [7442, 3671, 155, 345, 918], [7442, 3671, 155, 345, 5575], [3017, 807, 2105, 1888, 6616], [4284, 5179, 7069, 345]]


#### Word Embedding Represntation

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

Anything we want to pass to the Embedding layer all the sentences should have same number of words. that would make us to create good Embedding matrix

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  807 7871 1888 5861]
 [   0    0    0    0  807 7871 1888 9764]
 [   0    0    0    0  807 9155 1888 3730]
 [   0    0    0 7442 3671  155  345  918]
 [   0    0    0 7442 3671  155  345 5575]
 [   0    0    0 3017  807 2105 1888 6616]
 [   0    0    0    0 4284 5179 7069  345]]


In [11]:
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 56ms/step
[[[ 0.02526272 -0.04426057 -0.03835852  0.02037145  0.00882966
   -0.03550377  0.00715662  0.04662659 -0.0490704  -0.02028999]
  [ 0.02526272 -0.04426057 -0.03835852  0.02037145  0.00882966
   -0.03550377  0.00715662  0.04662659 -0.0490704  -0.02028999]
  [ 0.02526272 -0.04426057 -0.03835852  0.02037145  0.00882966
   -0.03550377  0.00715662  0.04662659 -0.0490704  -0.02028999]
  [ 0.02526272 -0.04426057 -0.03835852  0.02037145  0.00882966
   -0.03550377  0.00715662  0.04662659 -0.0490704  -0.02028999]
  [-0.02846046 -0.00096311  0.00727531 -0.02488121  0.04949904
   -0.04642006  0.02443249  0.0395347   0.01273345 -0.02657473]
  [ 0.00818895 -0.01364698 -0.01733525  0.04423208 -0.03693622
   -0.00411998 -0.0244872  -0.0240278   0.01743006 -0.00295252]
  [-0.03277515 -0.03898083  0.00127069  0.02848253  0.03372754
    0.00748473  0.01752602 -0.02080494  0.04573316 -0.02019729]
  [ 0.02998636  0.04493191 -0.03897979 -0.00811443  0.01208

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0,  807, 7871, 1888, 5861], dtype=int32)

In [16]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 11ms/step
[[ 0.02526272 -0.04426057 -0.03835852  0.02037145  0.00882966 -0.03550377
   0.00715662  0.04662659 -0.0490704  -0.02028999]
 [ 0.02526272 -0.04426057 -0.03835852  0.02037145  0.00882966 -0.03550377
   0.00715662  0.04662659 -0.0490704  -0.02028999]
 [ 0.02526272 -0.04426057 -0.03835852  0.02037145  0.00882966 -0.03550377
   0.00715662  0.04662659 -0.0490704  -0.02028999]
 [ 0.02526272 -0.04426057 -0.03835852  0.02037145  0.00882966 -0.03550377
   0.00715662  0.04662659 -0.0490704  -0.02028999]
 [-0.02846046 -0.00096311  0.00727531 -0.02488121  0.04949904 -0.04642006
   0.02443249  0.0395347   0.01273345 -0.02657473]
 [ 0.00818895 -0.01364698 -0.01733525  0.04423208 -0.03693622 -0.00411998
  -0.0244872  -0.0240278   0.01743006 -0.00295252]
 [-0.03277515 -0.03898083  0.00127069  0.02848253  0.03372754  0.00748473
   0.01752602 -0.02080494  0.04573316 -0.02019729]
 [ 0.02998636  0.04493191 -0.03897979 -0.00811443  0.01208295  0.00197517